### ISSUE TITLE
[FEATURE]: Update Readme

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#1009]
### Feature Name

Update Readme

### Your Name

Daniel Wu

### Description

- Make npm step more clear
- Apply for student developer park:
https://education.github.com/pack
- Add instructions for intel Macs

**Comment by karkir0003** [comment]
@farisdurrani @dwu359 is this task completed?

**Comment by farisdurrani** [comment]
Closed as duplicate to #1010
