### ISSUE TITLE
[FEATURE]: Improve README Instructions

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#1010]
### Feature Name

Improve README Instructions

### Your Name

Faris Durrani

### Description

We attach a few installation recommendations from today's new member meeting:
1. What you should be seeing if the installation runs correctly
1. Suggesting restart after installing WSL
1. Adding NVM to PATH on Windows after installing
1. Adding GitHub Student Dev Packet link

**Comment by karkir0003** [comment]
@farisdurrani did we ever finish this?

**Comment by farisdurrani** [comment]
Not really

**Comment by karkir0003** [comment]
I see. @farisdurrani would you be able to send out a PR on these updates within the next few days?

**Comment by karkir0003** [comment]
I think it'd be good to make sure our engineering documentation is up to date in case people are having confusions in the future
