### ISSUE TITLE
[FEATURE]: Fix Trainspace POST endpoints to support new Training Flow

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#1073]
### Feature Name

Fix Trainspace POST endpoints to allow to support new Training Flow

### Your Name

Daniel Wu

### Description

**Problem**
When a trainspace is currently created, it is separated by steps and categories rather than by blocks. 

**Approach**
We want modify the trainspace POST endpoints to store the following in a trainspace table in dynamo:
- id
- date created
- user id
- list of datasets
- list of models
- list of blocks

Dataset:
- Source (default, s3)
- dataset id
- s3 url (if s3 source)

Models:
- Name
- Model id
- Dataset id
- list of model versions:
- Model versions:
   - Name of model version
   - s3 url to model

Blocks (stored within trainspace item):
-  Block id
- Type of block
- Other info based on the type of block
- Run data
   - s3 url, string, number, etc based on the type of block

**Any other considerations**
The trainspace POST endpoints currently run serverlessly and are written as Infra as Code through SST.

**Comment by karkir0003** [comment]
whats the purpose of blocks table @dwu359
