### ISSUE TITLE
[FEATURE]: POST Endpoint to Update Trainspace

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#1074]
### Feature Name

POST Endpoint to Update Trainspace

### Your Name

Daniel Wu

### Description

https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/1073
Except it's for updating a trainspace rather than creating it

**Comment by karkir0003** [comment]
is this independent of #1073 @dwu359

**Comment by karkir0003** [comment]
Daniel, Mughdesh and I met on Discord to get good understanding of the ask/request
