### ISSUE TITLE
[FEATURE]: Create Pipeline to Deploy Dockerized Backend on g4dn Instances

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#1075]
### Feature Name

Create Pipeline to Deploy Dockerized Backend on g4dn Instances

### Your Name

Daniel Wu

### Description

**Problem**
We need a way to automate the deployment of our training backend to our prod environment. We plan to have the prod environment of a training backend to be EC2 G4dn instances. 

The EC2 G4dn instances already exist in us east 1.
**Approach**
- Create a Github workflow that automatically dockerizes the training backend and uploads to image to ECR

**Comment by karkir0003** [comment]
@andrewpeng02 is this all complete?

**Comment by andrewpeng02** [comment]
Yes
