### ISSUE TITLE
[BUG]: pnpm install fix in dlp-cli

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#1077]
### Operating system

MacOS, Windows

### Bug description

When we run `dlp-cli frontend install` on the most recent version of `dlp-cli`, there is an error that arises due to `pnpm` not being installed in order to setup the frontend. This seems to be due to the `dlp-cli` using `yarn` to install the project when we migrated to `pnpm` as the dependency manager for the frontend. 

Fix:
1. Go into `dlp-cli` [repo ](https://github.com/DSGT-DLP/dlp-cli/tree/main)and look for `cmd/frontend/install` folder and update that `.go` file to enforce installation of `pnpm` prior to running `pnpm install`
2. Test that `dlp-cli frontend install` works seamlessly after step 1
3. Make a Pull Request and tag @dwu359 on it
4. Merge the PR and trigger `goreleaser` to release a minor version upgrade to the CLI (for both `brew` and `scoop`)

### Steps to reproduce

1. Clone DLP Repo
2. `dlp-cli frontend install` after having the Node V20/corresponding npm installed
3. Error arises

**Comment by hartejsingh12** [comment]
Successfully merged in the dlp-cli repository. Therefore, this issue is done and will be closed.
