### ISSUE TITLE
[BUG]: Remove yarn.lock file

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#1117]
### Operating system

N/A

### Bug description

**Context**
DLP transitioned from `yarn` to `pnpm` as the package manager for frontend dependencies. However, in the `frontend/` directory of the project, the `yarn.lock` file still persists. We don't require this file as a `pnpm-lock.yaml` file is generated from `pnpm`. 

**Solution:**
1. Remove the `yarn.lock` file from `frontend/` directory/folder. 
2. Create a pull request and tag @Project Lead in discord (with link to the pull request)

### Steps to reproduce

Examine the `frontend/` directory and check that the `yarn.lock` file is there

**Comment by karkir0003** [comment]
Steps on how to test your changes:
1. After removing the `yarn.lock` file from `frontend/`, please run `dlp-cli frontend start` and verify that `localhost:3000` renders the app. You will also need to run `dlp-cli backend start` in a separate terminal window to load up the backend

**Comment by farisdurrani** [comment]
Completed in a previous PR
