### ISSUE TITLE
[FEATURE]: Update DynamoDB Tables and Infra-Code to support new table layout

### ISSUE THREAD

**Issue by MugPand** [DSGT-DLP/Deep-Learning-Playground#1123]
### Feature Name

Update DynamoDB Tables and Infra-Code to support new table layout

### Your Name

Mugdhesh

### Description

Update dynamoDB tables and infra-code to replicate the following design:

<img width="637" alt="image" src="https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/35412291/9ce63b54-fcdf-48a8-8a37-77b9c34ded1a">

**Comment by karkir0003** [comment]
@MugPand can you add user id/uid as a field for the models table?
