### ISSUE TITLE
[FEATURE]: Migrate training into Celery

### ISSUE THREAD

**Issue by andrewpeng02** [DSGT-DLP/Deep-Learning-Playground#1136]
### Feature Name

Migrate training into Celery

### Your Name

Andrew Peng

### Description

Currently, we do the training during the HTTP request. I plan on changing the train HTTP endpoints by scheduling a train job via Celery and returning the job id in the request. This offers numerous advantages
- Long training tasks (>2 min) shouldn't be done in an HTTP request. Scheduling the training job will allow the endpoint to return quickly
- Eventually, we can decouple the backend with the training, so that we can use cheaper EC2 instances for the Django backend, and GPU instances for the actual training

Notifying the user will be done in websockets in this issue (https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/920#event-11765625412), for now I'll create an HTTP endpoint to retrieve the training results that the user can ping.

**Comment by karkir0003** [comment]
@andrewpeng02 thanks for writing this issue. Is this docs on celery the updated ones: https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
