### ISSUE TITLE
[FEATURE]: Create Terraform scripts for ECS backend

### ISSUE THREAD

**Issue by andrewpeng02** [DSGT-DLP/Deep-Learning-Playground#1137]
### Feature Name

Create Terraform scripts for ECS backend

### Your Name

Andrew Peng

### Description
Create Terraform scripts to deploy the backend to ECS fargate and deploy the training containers on ECS:
Backend ECS cluster
      a. ASG as a Capacity Provider  
          1. EC2 target group
      b. Training ECS service (EC2 launch type)
          1. Training load balancer
          2. Deploy backend ECS task
      c. Django ECS service (Fargate)

**Comment by karkir0003** [comment]
@andrewpeng02 could you detail what infra you need to create here so that the project leads are in the loop
