### ISSUE TITLE
Upgrade CSV Input Table

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#412]
**Describe the solution you'd like**
The current CSV Input table, populated after a user uploads a CSV, is using 'react-csv' and populating all rows. We want to transfer to use [MUI's Data Table](https://mui.com/material-ui/react-table/#data-table) for better UI and standardization. The new table should restrict the number of rows displayed to an arbitrary reasonable constant

**Setup Instructions (what branch to work off of)**
Create branch `csv-table` off of `frontend`.

**Comment by karkir0003** [comment]
@farisdurrani @mateo0203 how's progress going on this?

**Comment by farisdurrani** [comment]
Resolved by z #552
