### ISSUE TITLE
Minor: change color of menu navbar icon

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#443]
**Describe the solution you'd like**
Currently, the collapsed navbar shows a black burger menu icon, which does not contrast well with the dark blue background. We need to change it to white or something light
![image](https://user-images.githubusercontent.com/40067313/194788344-54ea2d70-e088-4d95-8e92-6b192c787fbb.png)

**Setup Instructions (what branch to work off of)**
Create branch off of frontend

**Comment by karkir0003** [comment]
@farisdurrani is this still relevant?

**Comment by farisdurrani** [comment]
No since we're redesigning the UI. Closing...

**Comment by karkir0003** [comment]
thx
