### ISSUE TITLE
Text Notification when training completes (success or fail)

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#527]
**Describe the solution you'd like**
Send users text message if they have configured it in their user settings. send sms notification after training completes (success or fail)

**Additional context**
Should be fairly understandable

**Setup Instructions (what branch to work off of)**

```
git checkout dev
git pull origin dev
git checkout -b sms-train-notification
```

**Comment by farisdurrani** [comment]
Closed as duplicate for #526
