### ISSUE TITLE
UI issue on dev branch

### ISSUE THREAD

**Issue by Dashrekker** [DSGT-DLP/Deep-Learning-Playground#541]
![image](https://user-images.githubusercontent.com/47958374/213956067-bf2bad0e-2443-4dbb-a915-39fad686db02.png)
After pulling from the dev branch on 1/10 the select button for image transformations suddenly grew wider.

**Comment by karkir0003** [comment]
@farisdurrani

**Comment by karkir0003** [comment]
https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/dev/frontend/playground-frontend/src/components/ImageModels/ImageModels.js#L225 - good starting point @farisdurrani
