### ISSUE TITLE
Docker compose to enable live-editing for Docker files

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#589]
**Describe the solution you'd like**
Create a docker-compose.yml file to enable Docker to load new changes to the files as we make new changes

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b docker-compose
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@farisdurrani status on this?

**Comment by farisdurrani** [comment]
Closed for non-importance
