### ISSUE TITLE
Recaptcha detection during sign up

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#687]
**Describe the bug**
users can register for account without completing recaptcha
**To Reproduce**

1. register a dummy account but do not complete recaptcha and press register

**Expected behavior**
error prompting user to complete recapcha

**Desktop (please complete the following information):**

- OS: mac, windows, other OS
- Browser: chrome and presumably other branches

**Additional context**
important issue to fix

**Comment by farisdurrani** [comment]
Issue does not seem to continue in the current dev branch, closing for now
