### ISSUE TITLE
Get Firebase token from email

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#704]
**Describe the solution you'd like**
Create a python script that uses the firebase-admin sdk to get a bearer token given an email.

**Additional context**
We plan to use this as a helper script for us to get the bearer token needed to make api calls to our backend through postman.

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout nextjs
git pull origin nextjs
git checkout -b <dev-branch-name-here>
```
FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@dwu359 i guess we wrote duplicates of this issue lol

**Comment by karkir0003** [comment]
i linked some detail on my version of this task for augusto: https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/703

**Comment by karkir0003** [comment]
closing this as duplicate

**Comment by dwu359** [comment]
Oh whoops didn't realize lol
