### ISSUE TITLE
Fix DLP Logo

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#705]
**Describe the bug**
Hover functionality on the DLP logo on the very top left in the Nav Bar doesn't work since the nextjs Image component doesn't really work too well with Bootstrap components. Also positioning of the logo is implemented in a hacky way (sorry had to implement something quick to get the nextjs upgrade through).

**To Reproduce**
Hover over the DLP logo.

**Expected behavior**
The logo should change color in the same way as the link next to it.

**Screenshots**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/54150946/231629201-f6923ffe-f09b-4e5f-9421-bd25c9acba20.png">

**Comment by karkir0003** [comment]
@farisdurrani @dwu359 are working with Amore (our logo designer) for a new logo

**Comment by farisdurrani** [comment]
1. Hover and click on the DLP logo
2. Once you hover, the Deep Learning Playground text will turn green

Assigned to @prishavall
