### ISSUE TITLE
Push image to ECR in effort to move to EKS

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#707]
**Describe the solution you'd like**
In the effort to move to Managed Kubernetes Service – Amazon EKS, the first step is to push the docker image to Elastic Container Registry using [put-image](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/put-image.html).

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b eks
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
this will be gh action driven? @farisdurrani

**Comment by karkir0003** [comment]
no need to base dev branch off of nextjs @farisdurrani
