### ISSUE TITLE
Upload files to S3

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#708]
**Describe the solution you'd like**
To handle even larger file uploads over the HTTP limits, we want to allow users to upload their files to S3 first before they can choose which files to use to send to the backend. The S3 URL will be sent instead of the heavier JSON-converted file to the backend for better performance. As a consequence, the frontend will handle the S3 file upload independently

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b s3-upload-files
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@farisdurrani who will we assign this task to?

**Comment by karkir0003** [comment]
no need to base dev branch off of nextjs @farisdurrani

**Comment by karkir0003** [comment]
@dwu359 progress on this?

**Comment by karkir0003** [comment]
@dwu359 progress on this?

**Comment by farisdurrani** [comment]
Done
