### ISSUE TITLE
Re-Implement Feedback Form For Nextjs

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#709]
**Describe the solution you'd like**
Currently, the feedback form displays on the current nextjs upgrade, but it doesn't have any form submission capabilities yet. Use the AWS lambda feedback form endpoint to re-implement feedback form submissions.

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout nextjs
git pull origin nextjs
git checkout -b feedback-form
```
FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
keep in mind aws lambda has 15 min time limit per request! @dwu359

**Comment by dwu359** [comment]
@karkir0003 That's true, feedback form submissions should take much less than 15 minutes, however. Faris told me that AWS lambda was the way that we handled feedback form submissions beforehand also.

**Comment by karkir0003** [comment]
oh ok. thats a relief
