### ISSUE TITLE
Re-Implement Tabular Training for NextJS Upgrade

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#715]
**Describe the solution you'd like**
Re-Implement tabular training for Nextjs Upgrade

**Setup Instructions (what branch to work off of)**
Run the following commands

```
git checkout nextjs
git pull origin nextjs
git checkout -b tabular```

FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
context @dwu359

**Comment by dwu359** [comment]
Basically I'll be re-implementing tabular train with a multi-step design rather than the singular page that we used to have to train models. @karkir0003

**Comment by karkir0003** [comment]
ah i see.

**Comment by karkir0003** [comment]
@dwu359 seems like we are revamping the training UI, so this task isn't needed (but technically complete)
