### ISSUE TITLE
Verify Re-Captcha Token within Firebase Authentication and feedback AWS Lambda Endpoint

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#716]
**Describe the solution you'd like**
Re-captcha tokens should be verified within any auth/backend/aws endpoints that use re-captcha to make sure that the user actually did the re-captcha.

**Additional context**
The firebase and feedback AWS Lambda endpoints currently don't verify re-captcha tokens within the endpoints.

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout nextjs
git pull origin nextjs
git checkout -b recaptcha-token
```
FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@dwu359 how easy is this task implementation and difficulty wise?

**Comment by karkir0003** [comment]
For recaptcha, this might be a good starting point: https://developers.google.com/recaptcha/docs/verify
