### ISSUE TITLE
Linux setup on OCI

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#722]
**Describe the solution you'd like**
Using our Oracle Cloud instance, we want to:
- set up a new account on Linux for yourself
- create shell script for setup, see here: https://docs.google.com/document/d/15NdgVO9VSzQNWbi_YZ2qB5twG9WuytKgx7rf380QsWY/edit
- create a dummy git commit from the SSH instance

**Additional context**
This is to help in case we bring the OCI instance down and have to set up everything again

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b oci-ssh
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@farisdurrani @prishavall status?

**Comment by farisdurrani** [comment]
Closing as not needed anymore
