### ISSUE TITLE
Remove white space under footer

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#728]
**Describe the solution you'd like**
Use CSS to remove white space under footer
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/40067313/235820841-5f75e02a-069c-4dda-8050-9b8b8f1a673d.png">

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b white-space-footer
```
FYI: If you are not able to immediately run `git checkout dev`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@farisdurrani who's assigned to this?
