### ISSUE TITLE
Pass UIDs to Backend From Middleware Rather Than Part of the Request Body from the Frontend

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#734]
**Describe the solution you'd like**
Backend endpoints should get the firebase user id from the middleware token verification logic rather than as part of the frontend request. This is to ensure that the uid used by any backend endpoint matches up with the bearer token passed in to the middleware (so that user A cannot make a request to the backend with the uid of user B, for example).

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout dev
git pull origin dev
git checkout -b nextjs
```
FYI: If you are not able to immediately run `git checkout next's`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
@archishmagoli so my understanding of this task is that currently in the frontend, when we pass user id, we explicitly specify a param called `uid` (eg: `request['user']['uid']`). However, on our backend endpoints, some of our api endpoints already require user to be authenticated, so we are sort of doing duplicate work. 

Sample frontend endpoint with the problem: https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/frontend/playground-frontend/src/features/Train/redux/trainspaceApi.ts#LL18C8-L24C13

Corresponding backend API endpoint: https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/backend/endpoints/s3_edpoints.py#L83

here, we pass in `auth.currentUser`, but then on the backend, we use `request["user"]["uid"]` to get the unique user id. 

What you want to do is that in the `backend/middleware.py` script, you should be using the bearer token to get the unique user id. 

One direction you can look into is the `firebase_admin` python sdk. 

this import `from firebase_admin import auth` could be a good start. 

Firebase Admin Python SDK docs: https://firebase.google.com/docs/reference/admin/python
