### ISSUE TITLE
Implement Image Training Flow

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#749]
**Describe the solution you'd like**
Implement/modify the backend endpoints & UI needed to create an Image trainspace.

**Additional context**
The way that we implemented Image model training before the refactorization of the training flow can be found here: https://datasciencegt-dlp.com/img-models

This should have about the same folder structure as Tabular: All Image specific code should be in src/features/Train/features/Image, split the code into components, constants, redux, types folders, etc. 
There are existing layout components in src/features/Train/components that would be helpful in creating the actual UI components for Image.
Existing train constants should be modified also to allow for an Image trainspace selection. 
Make sure to modularize Image also by adding an index file to handle exporting of elements outside of Image (Tabular also has an example of this).
Please ask questions if you have any, especially for this feature (since I made some opinionated decisions on the structure of the train code on the frontend that should either be kept or changed to maintain consistency)!

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout nextjs
git pull origin nextjs
git checkout -b image-train
```
FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by AmyCGT** [comment]
https://github.com/DSGT-DLP/Deep-Learning-Playground/pull/782
