### ISSUE TITLE
When wrong login credentials are entered, a banner pops up but the page goes blank

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#778]
**Describe the bug**
When wrong login credentials are entered, a banner pops up but the page goes blank

**To Reproduce**

1. Login with some fake email password credentials
2. You will see this page: 
![image](https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/40067313/cca4bba3-aa35-45e0-890c-92c0dbac297c)

**Expected behavior**
The banner (toast) should show and the form should clear out, but otherwise, the page should remain unchanged

**Setup Instructions (what branch to work off of)**
Run the following commands

git checkout nextjs
git pull origin nextjs
git checkout -b fix-toast-incorrect-login
FYI: If you are not able to immediately run git checkout nextjs, make sure you commit your changes in the current branch or run git stash and then execute the above commands

**Comment by karkir0003** [comment]
do u know how to fix it @farisdurrani ?

**Comment by farisdurrani** [comment]
It has to do with the ThunkAPI and how it's handling the Firebase login error issue. For some reason, all the HTML elements other than the React Toastify container gets deleted

![image](https://github.com/DSGT-DLP/Deep-Learning-Playground/assets/40067313/39a7d1fb-89b5-4cb6-8b37-74baa8e75387)

**Comment by karkir0003** [comment]
@anikethswain Daniel merged in a PR that should fix this bug. Can you do the following

```
git checkout nextjs
git pull origin nextjs
```
and then spin up the frontend/backend as usual.
