### ISSUE TITLE
quick shell script for developers to run in order to setup their dev branch for a given github issue

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#786]
**Describe the solution you'd like**
Everytime we write a github issue, we want developers to work off of a dev branch for protection of the mainline. 

However, in each issue description, we end up having to repeat the same steps on how to create a dev branch (see the **Setup Instructions (what branch to work off of)**).

To alleviate this problem, we should setup a quick shell script that takes the name of a proposed dev branch and automatically setup the development branch with one run of the script. 

**Additional context**
Test that the script works on creating a dummy branch and tracking local/remote properly

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout nextjs
git pull origin nextjs
git checkout -b branch-setup-sh-script
```
FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

**Comment by karkir0003** [comment]
Extension idea (Could be overengineering. If so, let @karkir0003 know): If you are able to get the basic shell script working, a followup item (as a stretch goal) could be to see if we can adapt the script to be able to enter an issue id (eg: #786) and parse the data to identify the name of the development branch and use that as input to setting up the development branch 

AKA: issue id/number --> proper setup of development branch for the given task

**Comment by karkir0003** [comment]
clarification on what to do:

suppose we had a shell script named `create-branch.sh`. i want to run the script as such `./create-branch.sh hello` where `hello` is the name of the branch. the desired behavior of the shell script should be executing the following

```
git stash
git checkout nextjs
git pull origin nextjs
git checkout -b hello
```

**Comment by karkir0003** [comment]
@yeaitsurya

**Comment by codingwithsurya** [comment]
hey i just pushed the code. Let me know if u see it and if its feasible.

**Comment by codingwithsurya** [comment]
@karkir0003

**Comment by karkir0003** [comment]
hey. taking a look
