### ISSUE TITLE
Remove Open API Validation Github action

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#825]
**Problem:** DLP team shifted to using Redocly to make pretty looking and interactive API docs. When we update `nextjs` branch, Redocly automatically validates the open api yaml files. Thus, our open api validation action at `.github/workflows/open-api-validation.yaml` is not needed. 

**Solution:** Remove the `open-api-validation.yaml` file at the path `.github/workflows/open-api-validation.yaml`

**Comment by codingwithsurya** [comment]
Hope this works!

**Comment by codingwithsurya** [comment]
@karkir0003 accidentally committed changes needed for Issue 825 to 824. And i already merged the pull request for issue 824. So this remove open api validation github issue is already taken care of in the issue 824 pull request.  You can probably go ahead and close this issue if everything is fine. Apologize for the confusion.
