### ISSUE TITLE
[FEATURE]: Spinner after clicking Train button

### ISSUE THREAD

**Issue by farisdurrani** [DSGT-DLP/Deep-Learning-Playground#861]
### Feature Name

Spinner after clicking Train button

### Your Name

Faris Durrani

### Description

After clicking on Train to train a dataset, there is a couple of seconds of lag where the screen seems frozen but the app is querying the backend. We want better UI feedback and we can simply do this by:
- adding a simple spinner [example](https://mui.com/material-ui/react-progress/) after the user clicks on Train
- disabling Train button while it's loading

**Comment by karkir0003** [comment]
@farisdurrani can you elaborate more on what files to take a look at to tackle this issue
