### ISSUE TITLE
Dependency Optimization for Poetry

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#872]
**Problem:** DLP's Python backend system has the risk of being bloated. We might be installing dependencies in poetry that don't seem to really get used in our code. We want to reduce the size of our docker images and speed up the build time

**Solution:** Use a dependency optimization tool to scan our code and remove any unused python dependencies. Came across [deptry](https://fpgmaas.github.io/deptry/rules-violations/) as a potential example. Feel free to look for any better alternatives

**Comment by karkir0003** [comment]
Branch setup instructions

```
git checkout nextjs
git pull origin nextjs
git checkout -b poetry-dep-optimization
```

If `git checkout nextjs` doesn't work, commit or `git stash` your changes in the current branch and then execute the above sequence of git commands

**Comment by karkir0003** [comment]
Some other solutions I came across from brief google search:

* https://www.tweag.io/blog/2023-03-14-announcing-fawltydeps/
* https://github.com/fredrikaverpil/creosote

**Comment by codingwithsurya** [comment]
some quick notes from "upgraded to poetry ..." pr 

- pytest should just be a dev dependency
- is docker dependency in backend/pyproject.toml needed?

**Comment by karkir0003** [comment]
i dont think so for docker. test what happens if we remove it. does the app function fine

**Comment by karkir0003** [comment]
@codingwithsurya

**Comment by codingwithsurya** [comment]
> i dont think so for docker. test what happens if we remove it. does the app function fine

just tested. yea it works just fine.

**Comment by codingwithsurya** [comment]
@karkir0003 have u checked this out: https://fpgmaas.github.io/deptry/
