### ISSUE TITLE
[BUG]: poetry-lock precommit hook not working

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#880]
### Operating system

Windows 11

### Bug description

I tried committing some changes to removing unused frontend tsx code. I didn't change the pyproject.toml and when I commit the change and the poetry-lock pre-commit hook runs, i get a failed build check even though i didn't touch any poetry dependency. 

Fix: update our poetry github action build check to make sure the `poetry.lock` file is up to date with `pyproject.toml` or identify a better workaround that isn't too slow

### Steps to reproduce

1. make some minor code change
2. run `git add .` followed by `git commit -m <message>`
3. see the pre-commit hooks running

**Comment by codingwithsurya** [comment]
@karkir0003 already tried this, but I was having same issue. I solved by updating dependencies and regenerating poetry lock file using:

`poetry update`

this is what worked for me in the last commit. Make sure you run `poetry update` in the correct subdirectories.

if that doesn't work, make sure to update and clean ur pre-commit cache.

```
pre-commit clean
pre-commit autoupdate
```

This is personally what worked for me, and I'm not sure why it's not working for @karkir0003. Some more info here:

https://github.com/python-poetry/poetry/issues/8189

**Comment by karkir0003** [comment]
hmm. thats weird. im having austin tsst this out @codingwithsurya

**Comment by karkir0003** [comment]
@Dashrekker @codingwithsurya is this solved?

**Comment by codingwithsurya** [comment]
> @Dashrekker @codingwithsurya is this solved?

this works on my end. 

i think this is more of a windows issue so you will have to test it on your end. @karkir0003
