### ISSUE TITLE
deprecate conda/ directory

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#885]
due to migration from conda --> poetry, we dont require an environment.yml file.

thus, conda/ directory doesnt contain much useful info for current state of dlp. please remove this directory

**Comment by codingwithsurya** [comment]
@karkir0003 we deleted the environment.yml file already i believe. We can close this issue.

**Comment by karkir0003** [comment]
but delete the conda/directory. still present in nextjs branch @codingwithsurya

**Comment by codingwithsurya** [comment]
> but delete the conda/directory. still present in nextjs branch @codingwithsurya

oh my bad i didnt see that.
