### ISSUE TITLE
[FEATURE]: Use Gunicorn to run training backend in prod

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#911]
### Feature Name

Use Gunicorn to run training backend in prod

### Your Name

Daniel Wu

### Description

Instead of Django's `python manage.py runserver`, using a Python WSGI HTTP Server like Gunicorn is the accepted way of running WSGI apps like Django in production. Install and configure Gunicorn to securely run /training's Django ninja app in production with multithreading.

**Comment by karkir0003** [comment]
documentation for gunicorn @dwu359

**Comment by dwu359** [comment]
> documentation for gunicorn @dwu359

[https://gunicorn.org/#docs](https://gunicorn.org/#docs)
