### ISSUE TITLE
[FEATURE]: Add the Rest of the CRUD Endpoints to SST

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#914]
### Feature Name

Add the rest of the CRUD API endpoints to SST

### Your Name

Daniel Wu

### Description

Serverless Stack Toolkit (SST) handles development and deployment of serverless stacks, simplifying the development experience for lambdas. More info here [https://www.youtube.com/watch?v=JY_d0vf-rfw](https://www.youtube.com/watch?v=JY_d0vf-rfw) and here [https://docs.sst.dev/](https://docs.sst.dev/).

Endpoint routes to add:
- POST /trainspace (creates a trainspace and returns the id)
- GET /trainspace/{id} (gets trainspace information given the id)
- GET /trainspace (lists all trainspaces of a user)
- DELETE /trainspace/{id} (deletes a trainspace given its id)
- DELETE /dataset/user/{type}/{filename} (deletes a user uploaded dataset)

All code will be in the `serverless` directory.

**Comment by karkir0003** [comment]
@dwu359 @alantao912 status on this?
