### ISSUE TITLE
[FEATURE]: Handle File Uploading on Frontend Using SST Endpoints

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#917]
### Feature Name

Handle File Uploading on Frontend Using SST Endpoints

### Your Name

Daniel Wu

### Description

The presigned upload url endpoint has been migrated from the backend to SST already. You can access it using the prod endpoint `https://em9iri9g4j.execute-api.us-west-2.amazonaws.com/` with route `GET /datasets/user/{type}/{filename}/presigned_upload_url`. Keep in mind that this endpoint requires a bearer token for authentication.

The frontend also currently uses RTK Queries to send requests to the backend. It's like `fetch` or `axios` but it is easier to integrate with Redux and has extra features. You may find the `Redux Devtools` extension also helpful.

This medium article is also pretty good at explaining how AWS presigned urls work: [https://medium.com/@aidan.hallett/securing-aws-s3-uploads-using-presigned-urls-aa821c13ae8d](https://medium.com/@aidan.hallett/securing-aws-s3-uploads-using-presigned-urls-aa821c13ae8d)

Modify the uploadDatasetFile RTK Query in `frontend/src/features/Train/redux/trainspaceApi.ts` to use the SST presigned_upload_url endpoint to upload user dataset files.

**Comment by karkir0003** [comment]
will the api endpoint base url be a constant? @dwu359

**Comment by noah-iversen** [comment]
> will the api endpoint base url be a constant? @dwu359

Did we end up deciding this?

**Comment by karkir0003** [comment]
noah merged this PR in
