### ISSUE TITLE
[BUG]: Login With GitHub Not Working

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#923]
### Operating system

MacOS Ventura 13.2.1

### Bug description

Logging in with GitHub doesn't redirect me to the dashboard. Probably something to do with timer in _app.ts deleting the expect-user=true local storage object too early, but need to investigate further

### Steps to reproduce

When attempting to login with Github  in DLP on Firefox, it stays at the /login page

**Comment by karkir0003** [comment]
@dwu359 this problem doesn't hapen in chrome? just firefox and safari?

**Comment by dwu359** [comment]
Yes, because Chrome is one of the only browsers that still allows third-party cookies by default I think, although that will start to change in 2024.
