### ISSUE TITLE
[FEATURE]: Update the Website's Favicon and Logo

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#928]
### Feature Name

Update The Favicon and Logo

### Your Name

Daniel Wu

### Description

Update the favicon from figma using this logo (use the one titled `Light`): [https://www.figma.com/file/LlJ1KHd7uNcqoFPpv68Pb4/DLP-Logo-Redesign?type=design&node-id=0%3A1&mode=design&t=InEmqLbmemiv9vKp-1](https://www.figma.com/file/LlJ1KHd7uNcqoFPpv68Pb4/DLP-Logo-Redesign?type=design&node-id=0%3A1&mode=design&t=InEmqLbmemiv9vKp-1)

Make sure to follow Next.js's way to do it: [https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons)

Also make sure that the logo within the website is updated too. Use an svg version of the logo if possible.

**Comment by karkir0003** [comment]
@dwu359 faris did this. closing the issue

**Comment by karkir0003** [comment]
complete
