### ISSUE TITLE
Custom Logger - Backend

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#929]
**Problem**
Currently, in the old training service, we have a custom logger class [here](https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/backend/dlp_logging/__init__.py). This custom logger gives us color coded output in the terminal to clearly identify the error logs, info logs, etc using the `logging` framework in python. 

**Solution**
Migrate this custom logger class to the Django backend. 

Refer to these resources for approach
* https://docs.djangoproject.com/en/4.2/topics/logging/
* https://docs.djangoproject.com/en/dev/ref/django-admin/#syntax-coloring

**Comment by farisdurrani** [comment]
Solved using `logger`
