### ISSUE TITLE
[FEATURE]: Use Conda + Poetry For Environment

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#944]
### Feature Name

Use Conda + Poetry For Environment

### Your Name

Daniel Wu

### Description

Poetry has awesome package management with its pyproject toml, but has trouble setting up cross language packages such as pytorch and doesn't manage python versions in its own envs. Conda does manage python versions in its own envs and has an easier time installing packages such as pytorch, but harder to add/remove packages and ensure the same environment for all collaborators. If possible, having the best qualities of the two work together would be fantastic.

**Comment by karkir0003** [comment]
@dwu359 status update:

1. Mamba setup seems to work

Is this issue done (at least discovery phase), but we have to update the README and then we mark as done

**Comment by dwu359** [comment]
Would like to create cli cmds that aids with this also, and then update README, and then we mark this as done

**Comment by dwu359** [comment]
I can work on creating/updating the cli cmds for that
