### ISSUE TITLE
[FEATURE]: Add 2FA to DSGT-DLPLAYGROUND

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#954]
### Feature Name

Add 2FA to DSGT-DLPLAYGROUND

### Your Name

Daniel Wu

### Description

Github requires 2FA for all accounts by October 13, 2023, which apparently includes the github account under DLP

**Comment by karkir0003** [comment]
@dwu359 would you be able to take care of this since you can access the bot acct
