### ISSUE TITLE
[FEATURE]: Create Beginner Project

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#958]
### Feature Name

Create Beginner Project

### Your Name

Daniel Wu

### Description

https://docs.google.com/document/d/1Nc6dgnVRUcLZiIG_msmDhH1eMcMZKwXA-xWjRYJbP6s/edit?usp=sharing

**Comment by karkir0003** [comment]
@dwu359 followup on status here?

**Comment by dwu359** [comment]
Just started on this, I plan to work more on it during standup + pair prog meeting on sunday

**Comment by karkir0003** [comment]
@dwu359 status on this issue?

**Comment by dwu359** [comment]
I think it's good enough for now, we can always add to it later or modify it as we see fit: [https://github.com/DSGT-DLP/dlp-practice/issues/1](https://github.com/DSGT-DLP/dlp-practice/issues/1)

**Comment by karkir0003** [comment]
so we mark as done @dwu359
