### ISSUE TITLE
[FEATURE]: Add IAM Role Per Person

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#959]
### Feature Name

Add IAM Role Per Person

### Your Name

Daniel Wu

### Description

Instead of everyone using dev_user IAM role, we can have everyone have their own IAM user and have everyone in the same user group for more granular permissions.

**Comment by karkir0003** [comment]
@dwu359 thoughts on how we'd set this up systematically

**Comment by karkir0003** [comment]
so then for every dev that joins, we need to create a user for them. anyway we can have a simple.way to do it (more self service way)

**Comment by dwu359** [comment]
Yeah ig we need to look into that further

**Comment by dwu359** [comment]
@karkir0003 User groups: Project lead, returning member, member

**Comment by karkir0003** [comment]
@dwu359 what permissions should returning member vs. member groups have in IAM?

**Comment by karkir0003** [comment]
@dwu359 this is completed through IAM identity center
