### ISSUE TITLE
[FEATURE]: Add -r flag to each command

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#966]
### Feature Name

Add -r flag to each command

### Your Name

Daniel Wu

### Description

For each command, adding a -r flag should print out bash cmds to the console instead of running the actual cmd, so the dev can copy/paste into the terminal and/or use as a reference in case if the dev is unable to execute dlp-cli's cmds for some reason. 
For example, dlp-cli backend start -r should print something like this:
Activate dlp env:
conda activate dlp
Start training backend:
poetry run python manage.py runserver .....

But of course worded and displayed better.
PTerm package may be worth looking into for making the console output look good.

**Comment by karkir0003** [comment]
@dwu359 eta on this?

**Comment by karkir0003** [comment]
nonetheless good idea!

**Comment by dwu359** [comment]
> @dwu359 eta on this?

There's a bunch of other important tasks that I'll need to do first, not sure yet. Anyone else who wants to can pick up this task, I don't expect this one to be that hard

**Comment by karkir0003** [comment]
@dwu359 is it a good issue someone new can take on?

**Comment by karkir0003** [comment]
deprioritized
