### ISSUE TITLE
[BUG]: Fix PyRight GitHub Action to Use Conda Environment

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#967]
### Operating system

Whatever Operating System Github Actions use (linux?)

### Bug description

Before running the pyright github action that runs a static type check on the backend, have it install the conda environment and poetry packages first.

### Steps to reproduce

PyRight currently will complain about basically every python package rn bc it doesn't install the conda environment yet.

**Comment by karkir0003** [comment]
this should be fixed by the github action workflow revamp project @dwu359

**Comment by karkir0003** [comment]
https://github.com/mamba-org/setup-micromamba

mamba setup github action

**Comment by karkir0003** [comment]
https://github.com/mamba-org/setup-micromamba/issues/148

thread i created with micromamba to discuss cache v3 compatibility

**Comment by karkir0003** [comment]
@dwu359 I updated the backend build check action to add poetry env to path before running pyright action. The changes are currently implemented in Prisha's PR (`training-test-migration`)
