### ISSUE TITLE
[FEATURE]: Explore Github Teams Usage

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#968]
### Feature Name

Explore Github Teams Usage

### Your Name

Daniel Wu

### Description

We should look into separating developers into teams (new members, returning members, project leads) and look into any settings that we can apply for that, such as changing the CODEOWNERS file to be teamwide

**Comment by karkir0003** [comment]
@farisdurrani @dwu359 can this be marked as done?

**Comment by karkir0003** [comment]
@dwu359 status update on this?

**Comment by karkir0003** [comment]
nv mind. didn't notice we marked this task as done in the project board. sorry for the inconvenience here
