### ISSUE TITLE
[FEATURE]: Update Logo

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#973]
### Feature Name

Update Favicon + Logo on website with new logo

### Your Name

Karthik Subramanian

### Description

Update the favicon + Logo in the navbar with new DLP Logo

**Comment by AniswagMC** [comment]
Hey Karthik, I'd love to help solve this issue. Just assign it to me and I'll get on with it.

**Comment by karkir0003** [comment]
@farisdurrani this task is finished? can you update status of this issue

**Comment by farisdurrani** [comment]
Yeah, closing...
