### ISSUE TITLE
[FEATURE]: Update README file

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#982]
### Feature Name

Update README File

### Your Name

Daniel Wu

### Description

The README file should be updated to reflect current installation procedures.
Programs: VSCode, Postman, Docker, GitKraken
Cmd tools: nvm, yarn, mamba, git, pip (for global install of ggshield and pre-commit)
dlp-cli
Additional tools later: aws-cli

**Comment by karkir0003** [comment]
@dwu359 eta on this?
