### ISSUE TITLE
[BUG]: Fix id-token cmd + other cmds so that it runs thru mamba

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#989]
### Operating system

MacOS Ventura 13.2.1

### Bug description

Running the id-token command doesn't work unless the mamba env is spun up already with `mamba activate dlp`. This can be fixed by adding `mamba run` to the commands in the dlp-cli. I likely forgot to do this with other commands if the id-token command doesn't do this automatically, so check to make sure that those commands are fixed also

### Steps to reproduce

Run the id-token command without the mamba environment activated.

**Comment by karkir0003** [comment]
@dwu359 are there any other cmds that have this problem besides the `id-token` command
