### ISSUE TITLE
[BUG]: Backend Architecture.md displays /backend architecture instead of /training

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#991]
### Operating system

N/A

### Bug description

https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/.github/Architecture.md

### Steps to reproduce

https://github.com/DSGT-DLP/Deep-Learning-Playground/blob/nextjs/.github/Architecture.md

**Comment by karkir0003** [comment]
Hey @LuHG18 , the main file to worry about for this task is `file_tree_generator.py` at the root directory of the project as I showed you today in 1:1. Please don't hesitate to reach out in the DLP Discord if you have any questions. Looking forward to a PR from you in 1-2 days

**Comment by karkir0003** [comment]
PR is approved, @LuHG18 just needs to merge the change
